# Role input data validation
# Based on https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_reuse_roles.html#role-argument-validation
argument_specs:
  # For the itop_core read task
  read:
    short_description: Read the iTop CMDB
    description:
      - Calling this task will allow you to query the iTop CMDB
    version_added: 1.2.1
    author:
      - Schirrms
    options:
      # Begin of common part, to be reproduced in each task
      itop_core_ws_auth_user:
        type: "str"
        required: false
        description: iTop Rest Username

      itop_core_ws_auth_pwd:
        type: "str"
        required: false
        description: iTop Rest Password

      itop_core_ws_auth_token:
        type: "str"
        required: false
        description: iTop Rest Password

      itop_core_root:
        type: "str"
        required: true
        description: iTop server URL

      itop_core_ws_version:
        type: "str"
        required: false
        default: "1.3"
        description: "Web Service version"

      itop_core_ws_ansible_uuid:
        type: "str"
        required: false
        default: "ANS_APP1"
        description: "UUID in iTop of the Ansible application to work with"

      itop_core_ws_ansible_inventory:
        type: "str"
        required: false
        default: "ANS_ITOP"
        description: "Name of the inventory to consider"
      # End of common part

      itop_core_read_obj_class:
        type: "str"
        required: true
        description: "Class of CI to read"

      itop_core_read_key:
        type: "str"
        required: true
        description:
          - "Set of attributes to be used for the reconciliation"
          - "or id of the record"

      itop_core_read_fields:
        type: "dict"
        required: true
        description: "Set of attributes to be sent back"

  # For the itop_core write task
  write:
    short_description: Write data to the iTop CMDB
    description:
      - Calling this task will allow you to create ur update an object in the iTop CMDB
    version_added: 1.2.1
    options:
      # Begin of common part, to be reproduced in each task
      itop_core_ws_auth_user:
        type: "str"
        required: false
        description: iTop Rest Username

      itop_core_ws_auth_pwd:
        type: "str"
        required: false
        description: iTop Rest Password

      itop_core_ws_auth_token:
        type: "str"
        required: false
        description: iTop Rest Password

      itop_core_root:
        type: "str"
        required: true
        description: iTop server URL

      itop_core_ws_version:
        type: "str"
        required: false
        default: "1.3"
        description: "Web Service version"

      itop_core_ws_ansible_uuid:
        type: "str"
        required: false
        default: "ANS_APP1"
        description: "UUID in iTop of the Ansible application to work with"

      itop_core_ws_ansible_inventory:
        type: "str"
        required: false
        default: "ANS_ITOP"
        description: "Name of the inventory to consider"
      # End of common part

      itop_core_write_obj_class:
        type: "str"
        required: true
        description: "Class of CI to create or update"

      itop_core_write_key:
        type: "str"
        required: true
        description:
          - "Set of attributes to be used for the reconciliation"
          - "or id of the record"

      itop_core_write_fields:
        type: "dict"
        required: true
        description: "Set of attributes to be written"

      itop_core_write_output_fields:
        type: "dict"
        required: false
        description:
          - "Set of attributes to be sent back"
          - "After creating or updating a CI, this task read the result and"
          - "Send back the new values in the dict `itop_core_write_output_values`"
          - "by default, the returned value list is the list defined in `itop_core_write_fields`"
          - "If `itop_core_write_output_fields` is set, then this define the list of values that will be sent back"

      itop_core_write_create_comment:
        type: "str"
        required: false
        description: "A comment set in iTop while creating an object"

      itop_core_write_update_comment:
        type: "str"
        required: false
        description: "A comment set in iTop while updating an object"

  # For the itop_core ispresent task
  ispresent:
    short_description: check if an iTop query give an answer and how many answers are given
    description:
      - Calling this task will allow you to get
      - The number of match of your query in `itop_core_ispresent_found_items`
      - The list of object id in `itop_core_ispresent_obj_key`
    version_added: 1.2.1
    options:
      # Begin of common part, to be reproduced in each task
      itop_core_ws_auth_user:
        type: "str"
        required: false
        description: iTop Rest Username

      itop_core_ws_auth_pwd:
        type: "str"
        required: false
        description: iTop Rest Password

      itop_core_ws_auth_token:
        type: "str"
        required: false
        description: iTop Rest Password

      itop_core_root:
        type: "str"
        required: true
        description: iTop server URL

      itop_core_ws_version:
        type: "str"
        required: false
        default: "1.3"
        description: "Web Service version"

      itop_core_ws_ansible_uuid:
        type: "str"
        required: false
        default: "ANS_APP1"
        description: "UUID in iTop of the Ansible application to work with"

      itop_core_ws_ansible_inventory:
        type: "str"
        required: false
        default: "ANS_ITOP"
        description: "Name of the inventory to consider"
      # End of common part

      itop_core_ispresent_obj_class:
        type: "str"
        required: true
        description: "Class of CI to create or update"

      itop_core_ispresent_key:
        type: "str"
        required: true
        description:
          - "Set of attributes to be used for the reconciliation"
          - "or id of the record"

  # For the itop_core ispresent task
  delete:
    short_description: Delete an item from iTop CMDB
    description:
      - Calling this task will allow you to delete an iTem in the CMDB if
      - The reconciliation give only one match and
      - the optionnal but highly recommended `itop_core_delete_simulate` is
      - set to 'false' (default value true, witch is harmless)
    version_added: 1.2.1
    options:
      # Begin of common part, to be reproduced in each task
      itop_core_ws_auth_user:
        type: "str"
        required: false
        description: iTop Rest Username

      itop_core_ws_auth_pwd:
        type: "str"
        required: false
        description: iTop Rest Password

      itop_core_ws_auth_token:
        type: "str"
        required: false
        description: iTop Rest Password

      itop_core_root:
        type: "str"
        required: true
        description: iTop server URL

      itop_core_ws_version:
        type: "str"
        required: false
        default: "1.3"
        description: "Web Service version"

      itop_core_ws_ansible_uuid:
        type: "str"
        required: false
        default: "ANS_APP1"
        description: "UUID in iTop of the Ansible application to work with"

      itop_core_ws_ansible_inventory:
        type: "str"
        required: false
        default: "ANS_ITOP"
        description: "Name of the inventory to consider"
      # End of common part

      itop_core_delete_obj_class:
        type: "str"
        required: true
        description: "Class of CI to delete"

      itop_core_delete_key:
        type: "str"
        required: true
        description:
          - "Set of attributes to be used for the reconciliation"
          - "or id of the record"

      itop_core_delete_simulate:
        type: "str"
        choices:
          - "false"
          - "true"
        required: false
        default: "true"
        description:
          - "Determines if the deletion is to be done"
          - "if set to 'false', the deletion will be done"
          - "if set to 'true', there will be no actual deletion"

      itop_core_delete_comment:
        type: "str"
        required: false
        description: "A comment set in iTop while deleting an object"
